### ISSUE TITLE
 ERROR:  Error installing redis:  redis requires Ruby version >= 2.2.2.

### ISSUE THREAD

**Issue by skramana1973** [makentenza/ocp-redis-cluster#5]
Step 6 : RUN echo "151.101.64.70 rubygems.org">> /etc/hosts && gem install redis
  | ---> Running in a4fec3352a9d
  | ERROR:  Error installing redis:
  | redis requires Ruby version >= 2.2.2.
  | error: build error: The command '/bin/sh -c echo "151.101.64.70 rubygems.org">> /etc/hosts && gem install redis' returned a non-zero code: 1

**Comment by makentenza** [comment]
@skramana1973 the container is using now ruby 2.4 and the issue is solved
